---
services:
  frontend:
    container_name: frontend
    image: ft_transcendence_frontend:v1
    build: ./frontend
    networks:
      - transcendence_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://frontend:80/",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  nginx:
    container_name: nginx
    image: ft_transcendence_nginx:v1
    build: ./nginx
    ports:
      - "8080:80"
    networks:
      - transcendence_network
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy

  backend:
    container_name: backend
    image: ft_transcendence_backend:v1
    build: ./backend
    networks:
      - transcendence_network

networks:
  transcendence_network:
    name: transcendence_network
