services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql

  flyway:
    image: flyway/flyway:9.25.1
    depends_on:
      - db
    command: -url=jdbc:postgresql://db:5432/app_db -user=app -password=app migrate
    volumes:
      - ../database/migrations:/flyway/sql

volumes:
  db_data: