FROM golang:1.25-alpine AS builder

WORKDIR /app

# Dépendances
COPY backend/go.mod backend/go.sum ./
RUN go mod download

# Code source
COPY backend/ .

# Build binaire
RUN go build -o server ./cmd/server/main.go

# Run stage
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/server .

EXPOSE 8080

CMD ["./server"]